#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch arm64 -O3 -DL_ENDIAN -Wall"
  #define PLATFORM "darwin64-arm64-cc"
  #define DATE "Fri Nov 20 11:21:10 MST 2020"
#endif
